name: kaa_app
description: KAA Mobility Platform - 자동차 관련 정보와 중고차 정보를 한 번에 찾는 앱

publish_to: 'none'
version: 1.5.0+31

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  image: ^4.1.7
  flutter_image_compress: ^2.3.0
  audioplayers: ^6.1.0

dependency_overrides:
  geolocator_android: 4.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
