org.gradle.jvmargs=-Xmx400m -XX:MaxMetaspaceSize=180m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.suppressUnsupportedCompileSdk=35
kotlin.daemon.jvm.options=-Xmx256m -XX:MaxMetaspaceSize=128m
kotlin.incremental=false
kotlin.incremental.android=false
